version: '3'
services:
  gateway_proxy:
    image: nginx
    volumes:
     - ./nginx/:/etc/nginx/
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    links:
     - gateway
  gateway:
    image: python:3.6.3
    volumes:
     - ./python/:/var/www/
    working_dir: /var/www/
    command: bash -c "pip3 install -r requirements.txt && gunicorn -b gateway:8080 --worker-class gevent app:APP"
