version: '3'
services:
  puma_proxy:
    image: nginx
    volumes:
     - ./nginx/:/etc/nginx/
    ports:
     - "9000:9000"
    links:
     - puma
  puma:
    build: ./ruby
    command: "bundle exec puma"