language: python
python:
  - "2.7"
  - "3.5"
# install step should be explict and pip install -r requirements.txt
script:
  - locust -f locustfile.py --no-web --host http://localhost -c 1 -n 2
# will change -c and -n once we actually have services running

branches:
   only:
     - master

notifications:
  email: false
